### ISSUE TITLE
Click under 2.7 discourages the use of unicode_literals

### ISSUE THREAD

**Issue by jason-technology** [joshland/btrfsmaint#2]
./btrfsmaint.py:241: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @click.pass_context
./btrfsmaint.py:288: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/

May just be cosmetic

**Comment by joshland** [comment]
FIxed in #4bb5784825a975631788c9985741b8e03e61caf3
